FROM ubuntu:15.04
RUN apt-get update
RUN apt-get install -y python3-pip build-essential libblas3gf libblas-doc libblas-dev liblapack3gf liblapack-doc liblapack-dev gfortran libncurses-dev
RUN pip3 install numpy
RUN pip3 install scipy
RUN pip3 install ipython[all]
